### ISSUE TITLE
Building bottles for umobj and others

### ISSUE THREAD

**Issue by zbeekman** [zbeekman/homebrew-umiacs#2]
Right now I have built [bottles for UMObj](https://github.com/UMIACS/homebrew-umiacs/blob/master/Formula/umobj.rb#L9) (Yosemite only) and have uploaded them to the object store in [a public bucket](https://obj.umiacs.umd.edu/homebrew-umiacs-bottles). I just gave @liammonahan full control access to that bucket, in the event that new formulae are added, or a new release of umobj is upgraded. 

I would be happy to transfer ownership of this bucket, or point the `bottle do` block in the [umobj formula](https://obj.umiacs.umd.edu/homebrew-umiacs-bottles) and future formulae to a different url to host bottles. Otherwise I’m happy keeping things the way they are too, just let me know what peoples preference is.

**Comment by liammonahan** [comment]
Hi Izaak,

I'm fine with things as they are.  Let's revisit if it becomes necessary.

Liam
